server:
  port:
    8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/OrisCW2
    username: postgres
    password: spirit39890
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db-changelog.xml

  freemarker:
    enabled: true
    template-loader-path: /WEB-INF/templates
    suffix: .ftl

  mail:
    host: smtp.gmail.com
    username: ${GMAIL}
    password: ${GMAIL_APP_PASS_ORISCW2}
    post: 465
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 10000
          timeout: 10000
          writeTimeout: 10000
          starttls:
            enable: true

mail:
  baseUrl: http://localhost:8080
  sender: Test Application
  from: ${spring.mail.username}
  subject: Please verify your account
  content: "Dear $name, please follow the link to verify your account: <a href=$url>VERIFY</a>"

logging:
  level:
    org:
      springframework:
        security: WARN
      liquibase: DEBUG