#spring.database=POSTGRESQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/OrisCW2
#spring.datasource.username=postgres
#spring.datasource.password=spirit39890
#spring.datasource.platform=
#spring.datasource.driver-class-name=org.postgresql.Driver
#hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect